version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      opentelemetry:
        patterns:
          - "OpenTelemetry*"
      serilog:
        patterns:
          - "Serilog*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
